### ISSUE TITLE
Arduino.h cannot be included in own library

### ISSUE THREAD

**Issue by PBahner** [arduino/arduino-pro-ide#204]
With the Arduino Pro IDE I cant include the `<Arduino.h>` in my header and cpp file.
![image](https://user-images.githubusercontent.com/49592255/73953706-15566580-4901-11ea-9fc2-bbbc80cbab29.png)

**Comment by owennewo** [comment]
I get the same.  

I believe it's just a linting error - i.e. if your Gleisbildpult.ino includes your Weiche.h and there are no compilation errors in Weiche.h then it will verify/upload. 

I'm also seeing linting errors on the 'standard libraries':
e.g. the servo library described here https://www.arduino.cc/en/Reference/Libraries

I have to ignore the errors and intellisense doesn't work for them either. But I can compile and upload.

**Comment by MicheleCioccarelli** [comment]
I have the same issue, but it works fine: it doesn't give any compiling or uploading errors.
it is just visual

**Comment by spoenemann** [comment]
#149 must be solved so clangd can find included libraries.

**Comment by per1234** [comment]
Hi @PBahner . Thanks so much for taking the time to report this!

This should now be working in [the new 0.1.4 release of Arduino Pro IDE](https://github.com/arduino/arduino-pro-ide/releases/tag/0.1.4).

If you try it out and find that the problem is still occurring, feel free to comment here and we'll investigate.
